/* This file was generated by SableCC (http://www.sablecc.org/). */

package Project2.node;

import Project2.analysis.*;

@SuppressWarnings("nls")
public final class TExcl extends Token
{
    public TExcl()
    {
        super.setText("!");
    }

    public TExcl(int line, int pos)
    {
        super.setText("!");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExcl(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExcl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExcl text.");
    }
}
